site:
  name: IPFlex
  site: 'https://ipflexproxy.com'
  base: '/'
  dashboard: 'https://dashboard.ipflex.ink'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M
  bingSiteVerificationId: 8D799482CF9CE9E195F399D5BD19E2DC
  s360SiteVerificationId: f2330f13ce1669019105431474dad8dd
  baiduSiteVerificationId: codeva-DsczgTJKSi  # 百度站长 ipflexproxy.com

# Default SEO metadata
metadata:
  title:
    default: IPFlex
    template: '%s — IPFlex'
  description: "全球领先的IP代理服务商，支持HTTP/SOCKS协议，提供免费测试和7*24小时技术支持。覆盖全球200+国家，拥有100万+优质IP资源，为企业和个人用户提供安全可靠的网络解决方案。"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: IPFlex
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  languages: ['en', 'zh']
  defaultLanguage: zh
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
  
    post:
      isEnabled: true
      permalink: '/blog/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
